"""add_age_height_weight_to_patients

Revision ID: e6a89442c56d
Revises: d61dc0437346
Create Date: 2026-06-05 16:14:49.044657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a89442c56d'
down_revision: Union[str, None] = 'd61dc0437346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # --- Data Backfill: Populate age, height, and weight for existing patients ---
    connection = op.get_bind()
    import random
    from datetime import date
    random.seed(42)

    patients = connection.execute(sa.text("SELECT id, date_of_birth FROM patients")).fetchall()
    
    for row in patients:
        p_id = row[0]
        dob = row[1]
        
        # Calculate age from date_of_birth
        if dob:
            if isinstance(dob, str):
                dob = date.fromisoformat(dob)
            today = date.today()
            age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
        else:
            age = None
            
        height = round(random.uniform(150.0, 195.0), 1)
        weight = round(random.uniform(50.0, 110.0), 1)
        
        connection.execute(
            sa.text("UPDATE patients SET age = :age, height = :height, weight = :weight WHERE id = :id"),
            {"age": age, "height": height, "weight": weight, "id": p_id}
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'weight')
    op.drop_column('patients', 'height')
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###
