"""create specialties and doctors tables

Revision ID: e7c4b56af4a1
Revises: ad8a1e4a0e0d
Create Date: 2026-06-26 12:41:07.386259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c4b56af4a1'
down_revision: Union[str, None] = 'ad8a1e4a0e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
