"""create specialties and doctors tables

Revision ID: ad8a1e4a0e0d
Revises: a9b8c7d6e5f4
Create Date: 2026-06-26 12:37:32.712574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad8a1e4a0e0d'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_specialties_category', 'specialties', ['category'], unique=False)
    op.create_index('ix_specialties_code', 'specialties', ['code'], unique=False)
    op.create_index('ix_specialties_is_active', 'specialties', ['is_active'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('specialty_id', sa.UUID(), nullable=False),
    sa.Column('license_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('contact_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('address', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('ix_doctors_employee_id', 'doctors', ['employee_id'], unique=False)
    op.create_index('ix_doctors_last_name', 'doctors', ['last_name'], unique=False)
    op.create_index('ix_doctors_last_name_first_name', 'doctors', ['last_name', 'first_name'], unique=False)
    op.create_index('ix_doctors_specialty_id', 'doctors', ['specialty_id'], unique=False)
    op.create_index('ix_doctors_status', 'doctors', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctors_status', table_name='doctors')
    op.drop_index('ix_doctors_specialty_id', table_name='doctors')
    op.drop_index('ix_doctors_last_name_first_name', table_name='doctors')
    op.drop_index('ix_doctors_last_name', table_name='doctors')
    op.drop_index('ix_doctors_employee_id', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_specialties_is_active', table_name='specialties')
    op.drop_index('ix_specialties_code', table_name='specialties')
    op.drop_index('ix_specialties_category', table_name='specialties')
    op.drop_table('specialties')
    # ### end Alembic commands ###
