"""create patients table

Revision ID: a71bef42bd17
Revises: 
Create Date: 2026-05-30 18:15:59.626253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a71bef42bd17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('marital_status', sa.String(length=30), nullable=False),
    sa.Column('ssn_last_four', sa.String(length=4), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('chronic_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('contact_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('address', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contact', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('insurance_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_index('ix_patients_date_of_birth', 'patients', ['date_of_birth'], unique=False)
    op.create_index('ix_patients_last_name', 'patients', ['last_name'], unique=False)
    op.create_index('ix_patients_last_name_first_name', 'patients', ['last_name', 'first_name'], unique=False)
    op.create_index('ix_patients_mrn', 'patients', ['mrn'], unique=False)
    op.create_index('ix_patients_status', 'patients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_status', table_name='patients')
    op.drop_index('ix_patients_mrn', table_name='patients')
    op.drop_index('ix_patients_last_name_first_name', table_name='patients')
    op.drop_index('ix_patients_last_name', table_name='patients')
    op.drop_index('ix_patients_date_of_birth', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
